20220209-1047

diff --git a/ansible/roles/03_aiops-get-storage-class/tasks/main.yml b/ansible/roles/03_aiops-get-storage-class/tasks/main.yml
--- a/ansible/roles/03_aiops-get-storage-class/tasks/main.yml
+++ b/ansible/roles/03_aiops-get-storage-class/tasks/main.yml
@@ -28,7 +28,7 @@
 # --------------------------------------------------------------------------------------------------------------------------------------
 # *************************************************************************************************************************************************
 - name: STORAGECLASS -       👓 Load parameters
-  include_vars: ./00_config_cp4waiops.yaml
+  include_vars: ../00_config_cp4waiops.yaml
 
 
 # *************************************************************************************************************************************************
@@ -60,7 +60,7 @@
 # --------------------------------------------------------------------------------------------------------------------------------------
 # Otherwise determine Storage Class
 # --------------------------------------------------------------------------------------------------------------------------------------
-- name: STORAGECLASS -       ☑️  Determine Storage Class
+- name: STORAGECLASS -       ☑️  Determine File Storage Class
   shell: |
       CLUSTER_NAME={{ CLUSTER_NAME.stdout_lines[0] }}
       if [[ $CLUSTER_NAME =~ "fyre.ibm.com" ]];
@@ -85,21 +85,92 @@
         fi
       fi
   register: INSTALL_DETECTED_STORAGECLASS
-  when: STORAGECLASS_FILE_OVERRIDE=="not_configured" or STORAGECLASS_BLOCK_OVERRIDE=="not_configured"
+  when: STORAGECLASS_FILE_OVERRIDE=="not_configured"
+
+
+
+# --------------------------------------------------------------------------------------------------------------------------------------
+# Otherwise determine Storage Class
+# --------------------------------------------------------------------------------------------------------------------------------------
+- name: STORAGECLASS -       ☑️  Determine Block Storage Class
+  shell: |
+      CLUSTER_NAME={{ CLUSTER_NAME.stdout_lines[0] }}
+      if [[ $CLUSTER_NAME =~ "fyre.ibm.com" ]];
+      then
+          echo "rook-ceph-block"
+      else
+        if [[ $CLUSTER_NAME =~ "appdomain.cloud" ]];
+        then
+            echo "ibmc-block-gold"
+        else
+          # Use Default Class (storageclass.kubernetes.io/is-default-class:true)
+          SC_DEFAULT_STRING=$(oc get sc | grep "(default)")
+          if [[ $SC_DEFAULT_STRING =~ "(default)" ]];
+          then
+            echo ${SC_DEFAULT_STRING//\(*} 
+          else
+            echo "No default StorageClass defined. Unable to determine what SC to use." 
+            echo "Please define one using storageclass.kubernetes.io/is-default-class:true"
+            echo "or set the STORAGECLASS_XXX_OVERRIDE in the configuration file."
+            exit 1
+          fi
+        fi
+      fi
+  register: INSTALL_DETECTED_BLOCK_STORAGECLASS
+  when: STORAGECLASS_BLOCK_OVERRIDE=="not_configured"
+
+
 
 # --------------------------------------------------------------------------------------------------------------------------------------
 # Set File Storage Class
 # --------------------------------------------------------------------------------------------------------------------------------------
-- name: STORAGECLASS -       💾 Set WAIOPS_STORAGE_CLASS_FILE={{ INSTALL_DETECTED_STORAGECLASS.stdout_lines[0] }}
-  set_fact: WAIOPS_STORAGE_CLASS_FILE={{ INSTALL_DETECTED_STORAGECLASS.stdout_lines[0] }} 
+- name: STORAGECLASS -       💾 Set STORAGE_CLASS_FILE={{ INSTALL_DETECTED_STORAGECLASS.stdout_lines[0] }}
+  set_fact: STORAGE_CLASS_FILE={{ INSTALL_DETECTED_STORAGECLASS.stdout_lines[0] }} 
   when: STORAGECLASS_FILE_OVERRIDE=="not_configured"
 
 # --------------------------------------------------------------------------------------------------------------------------------------
 # Set Large Block Storage Class to same value
 # --------------------------------------------------------------------------------------------------------------------------------------
-- name: STORAGECLASS -       💾 Set WAIOPS_STORAGE_CLASS_LARGE_BLOCK={{ INSTALL_DETECTED_STORAGECLASS.stdout_lines[0] }} 
-  set_fact: WAIOPS_STORAGE_CLASS_LARGE_BLOCK={{ INSTALL_DETECTED_STORAGECLASS.stdout_lines[0] }} 
+- name: STORAGECLASS -       💾 Set STORAGE_CLASS_LARGE_BLOCK={{ INSTALL_DETECTED_BLOCK_STORAGECLASS.stdout_lines[0] }} 
+  set_fact: STORAGE_CLASS_LARGE_BLOCK={{ INSTALL_DETECTED_BLOCK_STORAGECLASS.stdout_lines[0] }} 
   when: STORAGECLASS_BLOCK_OVERRIDE=="not_configured" 
+
+
+
+
+# --------------------------------------------------------------------------------------------------------------------------------------
+# Check File Storage Class exists
+# --------------------------------------------------------------------------------------------------------------------------------------
+- name: STORAGECLASS -       ☑️  Check File Storage Class exists {{ STORAGE_CLASS_FILE }}
+  shell: |
+          SC_EXISTS=$(oc get sc {{ STORAGE_CLASS_FILE }} --ignore-not-found --no-headers| wc -l|tr -d ' ')
+          if [[ $SC_EXISTS -gt 0 ]];
+          then
+            echo "OK"
+          else
+            echo "Storage Class does not exist!"
+            echo "Please revioew your block storage class or set the STORAGECLASS_XXX_OVERRIDE in the configuration file."
+            exit 1
+          fi     
+  register: INSTALL_DETECTED_BLOCK_STORAGECLASS
+
+
+
+# --------------------------------------------------------------------------------------------------------------------------------------
+# Check Large Block Storage Class exists
+# --------------------------------------------------------------------------------------------------------------------------------------
+- name: STORAGECLASS -       ☑️  Check Large Block Storage Class exists {{ STORAGE_CLASS_LARGE_BLOCK }}
+  shell: |
+          SC_EXISTS=$(oc get sc {{ STORAGE_CLASS_LARGE_BLOCK }} --ignore-not-found --no-headers| wc -l|tr -d ' ')
+          if [[ $SC_EXISTS -gt 0 ]];
+          then
+            echo "OK"
+          else
+            echo "Storage Class does not exist!"
+            echo "Please revioew your block storage class or set the STORAGECLASS_XXX_OVERRIDE in the configuration file."
+            exit 1
+          fi     
+  register: INSTALL_DETECTED_BLOCK_STORAGECLASS
 
 
 
